name: Context Examples

on: ['push']

jobs:
  my-context:
    runs-on: ubuntu-latest
    steps:
      - name: "My Step"
        run: |
          echo "Hello! $MY_ACTION"
          echo "Actor! $MY_ACTOR"
        env:
          MY_ACTION: ${{ github.action }}
          MY_ACTOR": ${{ github.triggering_actor }}
      - name: "Second Step"
        run: echo "Second step! $MY_ACTOR"
        env:
          MY_ACTOR": ${{ github.triggering_actor }}
