name: Context Examples

on: ['push']

jobs:
  my-context:
    runs-on: ubuntu-latest
    steps:
      - name: "My Step"
        run: echo "Hello! $MY_ACTION"
        env:
          MY_ACTION: ${{ github.action }}
      - name: "Second Step"
        run: echo "Second step! $MY_SECOND_STEP"
        env:
          MY_SECOND_STEP": ${{ github.actor }}
